CREATE TABLE IF NOT EXISTS creatures (
    page_id         INTEGER PRIMARY KEY REFERENCES raw_pages(page_id),
    name            TEXT NOT NULL,
    hp              INTEGER,
    exp             INTEGER,
    boss            TEXT,
    is_boss         BOOLEAN DEFAULT FALSE,
    boss_type       TEXT,
    boss_cooldown   TEXT,
    boss_timeout    TEXT,
    summon_cost     INTEGER,
    convince_cost   INTEGER,
    illusionable    BOOLEAN,
    creature_class  TEXT,
    primary_type    TEXT,
    secondary_type  TEXT,
    pushable        BOOLEAN,
    push_objects    BOOLEAN,
    speed           INTEGER,
    charm_points    INTEGER,
    defense         INTEGER,
    mitigation      NUMERIC(5,2),
    occurrence      TEXT,
    difficulty      TEXT,
    max_damage      INTEGER,
    -- Abilities by damage type
    hab_physical    TEXT,
    hab_earth       TEXT,
    hab_fire        TEXT,
    hab_death       TEXT,
    hab_energy      TEXT,
    hab_holy        TEXT,
    hab_ice         TEXT,
    hab_lifedrain   TEXT,
    hab_manadrain   TEXT,
    hab_drowning    TEXT,
    hab_healing     TEXT,
    hab_invisible   TEXT,
    hab_speed       TEXT,
    hab_debuff      TEXT,
    hab_summon      TEXT,
    hab_drunk       TEXT,
    hab_paralyze    TEXT,
    hab_antitrap    TEXT,
    -- Damage modifiers (percentage, e.g. 100 = 100%)
    physical_mod    INTEGER,
    earth_mod       INTEGER,
    fire_mod        INTEGER,
    death_mod       INTEGER,
    energy_mod      INTEGER,
    holy_mod        INTEGER,
    ice_mod         INTEGER,
    heal_mod        INTEGER,
    reflects        TEXT,
    immunities      TEXT,
    ignores_fields  TEXT,
    implemented     TEXT,
    removed         TEXT,
    respawn_blocked BOOLEAN,
    behavior        TEXT,
    sounds          TEXT,
    location_raid   TEXT,
    -- Loot tiers
    loot_common     TEXT,
    loot_uncommon   TEXT,
    loot_semi_rare  TEXT,
    loot_rare       TEXT,
    loot_very_rare  TEXT,
    loot_event      TEXT,
    loot_raid       TEXT,
    notes           TEXT,
    history         TEXT
);

CREATE INDEX IF NOT EXISTS idx_creatures_name ON creatures (name);
CREATE INDEX IF NOT EXISTS idx_creatures_type ON creatures (primary_type);
